INSERT INTO products (name, brand, description, price, stock_quantity, image_url, category) VALUES
('Chanel No. 5', 'Chanel', 'A timeless and legendary floral fragrance.', 132.00, 50, 'http://localhost:8080/images/chanel-no5.jpg', 'Floral'),
('Black Opium', 'Yves Saint Laurent', 'A highly addictive feminine fragrance from YSL.', 112.00, 30, 'http://localhost:8080/images/black-opium.jpg', 'Oriental'),
('La Vie Est Belle', 'Lancôme', 'An elegant composition of iris and patchouli.', 98.00, 45, 'http://localhost:8080/images/la-vie-est-belle.jpg', 'Floral'),
('Acqua di Gio', 'Giorgio Armani', 'Aquatic, aromatic fragrance inspired by the Mediterranean sea.', 95.00, 100, 'http://localhost:8080/images/acqua-di-gio.jpg', 'Aquatic'),
('Bleu de Chanel', 'Chanel', 'A woody aromatic fragrance for the man who defies convention.', 145.00, 20, 'http://localhost:8080/images/bleu-de-chanel.jpg', 'Woody'),
('Flowerbomb', 'Viktor & Rolf', 'An explosive floral bouquet.', 165.00, 15, 'http://localhost:8080/images/flowerbomb.jpg', 'Floral Oriental'),
('Sauvage', 'Dior', 'A radically fresh composition, both raw and noble.', 110.00, 60, 'http://localhost:8080/images/sauvage.jpg', 'Fougère'),
('Light Blue', 'Dolce & Gabbana', 'A stunning perfume, overwhelming and irresistible like the joy of living.', 89.00, 80, 'http://localhost:8080/images/light-blue.jpg', 'Citrus'),
('Good Girl', 'Carolina Herrera', 'A sensual, evocative fragrance born of the beautiful contradictions of modern women.', 120.00, 25, 'http://localhost:8080/images/good-girl.jpg', 'Oriental Floral'),
('Oud Wood', 'Tom Ford', 'Rare, exotic, distinctive.', 210.00, 10, 'http://localhost:8080/images/oud-wood.jpg', 'Woody Oud'),
('Miss Dior', 'Dior', 'Fresh rose and peony floral trail with a soft feminine finish.', 135.00, 35, 'http://localhost:8080/images/miss-dior.jpg', 'Floral'),
('Coco Mademoiselle', 'Chanel', 'Sparkling citrus opening with sensual patchouli and florals.', 155.00, 28, 'http://localhost:8080/images/coco-mademoiselle.jpg', 'Oriental Floral'),
('J''adore', 'Dior', 'Elegant white floral bouquet with luminous fruity nuances.', 142.00, 32, 'http://localhost:8080/images/jadore.jpg', 'Floral'),
('Euphoria', 'Calvin Klein', 'Dark fruity oriental scent with creamy amber depth.', 85.00, 40, 'http://localhost:8080/images/euphoria.jpg', 'Oriental'),
('Chance', 'Chanel', 'Bright floral fragrance with pink pepper and jasmine notes.', 148.00, 26, 'http://localhost:8080/images/chance.jpg', 'Floral'),
('212 VIP', 'Carolina Herrera', 'Playful floral oriental scent with warm sweet undertones.', 95.00, 44, 'http://localhost:8080/images/212-vip.jpg', 'Floral Oriental'),
('Si', 'Giorgio Armani', 'Modern floral chypre with blackcurrant and vanilla accord.', 118.00, 38, 'http://localhost:8080/images/si-armani.jpg', 'Floral'),
('Libre', 'YSL', 'Floral oriental composition with lavender and orange blossom.', 125.00, 36, 'http://localhost:8080/images/libre.jpg', 'Floral Oriental'),
('Baccarat Rouge 540', 'Maison Margiela', 'Woody floral signature with radiant amber and saffron.', 325.00, 12, 'http://localhost:8080/images/baccarat-rouge.jpg', 'Woody Floral'),
('Alien', 'Thierry Mugler', 'Intense oriental woody perfume with jasmine and amber.', 99.00, 30, 'http://localhost:8080/images/alien.jpg', 'Oriental Woody'),
('Angel', 'Thierry Mugler', 'Iconic oriental fragrance with sweet and spicy depth.', 92.00, 34, 'http://localhost:8080/images/angel.jpg', 'Oriental'),
('Olympéa', 'Paco Rabanne', 'Salty vanilla oriental floral with smooth sensual warmth.', 88.00, 29, 'http://localhost:8080/images/olympea.jpg', 'Oriental Floral'),
('1 Million', 'Paco Rabanne', 'Bold oriental scent with spicy leather and amber notes.', 97.00, 33, 'http://localhost:8080/images/1-million.jpg', 'Oriental'),
('Invictus', 'Paco Rabanne', 'Fresh aquatic fragrance with marine and grapefruit accord.', 94.00, 41, 'http://localhost:8080/images/invictus.jpg', 'Aquatic'),
('Aventus', 'Creed', 'Fruity chypre masterpiece blending pineapple, birch, and musk.', 435.00, 8, 'http://localhost:8080/images/aventus.jpg', 'Fruity Chypre');
